version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/gtac-demo
permissions:
  - object: /home/ubuntu/gtac-demo
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: before_install.sh
      runas: ec2-user
  AfterInstall:
    - location: after_install.sh
      runas: ec2-user