version: 0.0
os: linux
#files:
#  - source: /app.wsgi
#    destination: /var/www/gtac-demo
#  - source: /
#    destination: /home/ec2-user/gtac-demo
#  - source: /conf/sample_app.conf
#    destination: /etc/httpd/conf.d
files:
  - source: /
    destination: /var/www/gtac-demo/index.html
hooks:
   AfterInstall:
    - location: install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server
      timeout: 300
      runas: root