version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/gtac-demo
hooks:
  AfterInstall:
    - location: before_install
      timeout: 300
      runas: ec2-user
   AfterInstall:
    - location: after_install
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_server
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: stop_server
      timeout: 300
      runas: ec2-user