version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/gtac-demo
    source: /gtac-demo/index.html
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: before_install.sh
      runas: ec2-user
    - location: start_server.sh
      runas: ec2-user
  ApplicationStop:
    - location: stop_server.sh
      runas: ec2-user
